### ISSUE TITLE
Add also real world examples

### ISSUE THREAD

**Issue by zokrezyl** [BrythonServer/brython-server#27]
Hi,

I find your project great, however would be useful to document implement a real case scenario that would automatically:

- pick up the sources from current dir
- do automagically brython-cli make_package <package_name>
- load and start main.py (or main if found) in a separate pane in the browser

Good luck and thanks for your work

**Comment by tiggerntatie** [comment]
Brython Server is itself a very specific application of [Brython ](https://brython.info/). I think you would find it more useful to visit the [documentation](https://github.com/brython-dev/brython) of Brython or search/ask questions on its [forum](https://groups.google.com/g/brython). I have found Brython's author and the community in general to be very helpful.

**Comment by zokrezyl** [comment]
great, thanks
